# Generated by Django 4.2.6 on 2023-10-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteexamples',
            name='id',
        ),
        migrations.AddField(
            model_name='websiteexamples',
            name='job_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='websiteexamples',
            name='job_images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
